apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:
  region: us-east-2
  version: 1.12

nodeGroups:
  - name: a
    labels: {role: workers}
    instanceType: c5.4xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    volumeSize: 100
    privateNetworking: true
    availabilityZones: a
    ssh:
      publicKeyPath: /home/bob/id_rsa4096.pub
    iam:
      withAddonPolicies:
        autoScaler: true

# cluster AZs must be set explicitly for single AZ nodegroup example to work
availabilityZones: a
